version: '3.8'

services:
  web:
    build: .
    container_name: php_native_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rahasia_portofolio
      MYSQL_DATABASE: db_native_project
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: pma_interface
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: